repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: fix-byte-order-marker
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
