name: Build and Push to GHCR

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: atlantis-terragrunt

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Log in to the Container registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - id: ghcr
      name: Build and push the Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        cache-from: type=gha,scope=build
        cache-to: type=gha,mode=max,scope=build
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
